### ISSUE TITLE
missing a word when function <formatQuoteLines> return List<string>

### ISSUE THREAD

**Issue by ilovecar** [graphicbeacon/aws_image_quote_gen_lambda#1]
when function try to split the sentence to List<sting>, if the sentence like this: 
"I am always doing that which "

expect:
line one:"I am always doing that"
line two:"which"

but the function only produce below:
line one:"I am always doing that"

and the line two just include ONE word will be missing..

---
in for loop, the ONE word line will be drop in some situation.. pls check it.

**Comment by graphicbeacon** [comment]
Great spot finding this bug and thanks for raising the PR. Added a comment on it.

**Comment by graphicbeacon** [comment]
Thanks for the fix. This is now merged.
